app/routes.py
from flask import Flask, request, jsonify, render_template, Blueprint, send_from_directory
from langchain_community.llms import Ollama
from langchain_community.vectorstores import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings.fastembed import FastEmbedEmbeddings
from langchain_community.document_loaders import PDFPlumberLoader
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain.chains.history_aware_retriever import create_history_aware_retriever
from .prompts import PROMPTS

import os
import shutil
import hashlib
import logging

# Define a blueprint
bp = Blueprint('main', __name__)

# Folder paths
folder_path = "data/db"
pdf_dir = "data/pdf"

# Path to the PDF directory for viewing PDFs
PDF_DIRECTORY = os.path.join(os.path.dirname(__file__), '..', 'data', 'pdf')

# Dictionary to keep track of PDF usage counts
pdf_usage_count = {}
query_usage_count = {}
chat_history = []

# Initialize the Ollama model
cached_llm = Ollama(model="llama3.1")

# Initialize the embedding model
embedding = FastEmbedEmbeddings()

# Initialize text splitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=2048,  # Increased chunk size for better context
    chunk_overlap=100,  # Increased overlap to maintain context between chunks
    length_function=len,
    is_separator_regex=False
)

def initialize_vector_store():
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
    # Perform a test operation to ensure proper initialization
    try:
        vector_store = Chroma(persist_directory=folder_path, embedding_function=embedding)
        # Example check to validate database
        if not vector_store.get():
            print("Vector store is empty or not properly initialized.")
            # Additional initialization steps if needed
        return vector_store
    except Exception as e:
        print(f"Error initializing vector store: {str(e)}")
        return None

initialize_vector_store()

if not os.path.exists(folder_path):
    print(f"Error: Directory {folder_path} does not exist.")

def file_exists(file_path):
    return os.path.isfile(file_path)

def compute_file_hash(file):
    """Compute the MD5 hash of a file."""
    hash_md5 = hashlib.md5()
    for chunk in iter(lambda: file.read(4096), b""):
        hash_md5.update(chunk)
    file.seek(0)  # Reset file pointer
    return hash_md5.hexdigest()


if not os.path.exists(folder_path):
    os.makedirs(folder_path)

if not os.path.exists(pdf_dir):
    os.makedirs(pdf_dir)

def preprocess_text(text):
    # Implement text cleaning steps
    text = text.strip().replace('\n', ' ').replace('\r', '')
    return text

class Document:
    def __init__(self, page_content, metadata=None):
        self.page_content = page_content
        self.metadata = metadata or {}

@bp.route('/')
def home():
    return render_template('index.html')

@bp.route('/prompts', methods=['GET'])
def get_prompts():
    try:
        # Convert PromptTemplate objects to a serializable format
        serializable_prompts = {key: str(value) for key, value in PROMPTS.items()}
        return jsonify(serializable_prompts)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@bp.route("/pdfManagement")
def pdfManagement():
    try:
        # Fetch the PDF and document statistics
        pdf_files = os.listdir("data/pdf")  # Adjust the path as needed
        vector_store = Chroma(persist_directory="data/db", embedding_function=embedding)
        db_data = vector_store.get()
        document_count = len(db_data.get("metadatas", []))
        
        return render_template("pdfManagement.html", pdf_count=len(pdf_files), doc_count=document_count)
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    
@bp.route("/ai", methods=["POST"])
def aiPost():
    query_usage_count = {}
    print("POST /ai called")
    json_content = request.json
    query = json_content.get("query")

    if not query:
        return jsonify({"error": "No 'query' found in JSON request"}), 400

    print(f"query: {query}")

    response = cached_llm.invoke(query)

    print(response)

    response_answer = {"answer": response}
    return jsonify(response_answer)

@bp.route("/ask_pdf", methods=["POST"])
def askPDFPost():
    query_usage_count = {}# Added for tracking PDF usage count
    print("POST /ask_pdf called")

    json_content = request.json
    query = json_content.get("query")
    prompt_type = json_content.get("promptType")  # Get the prompt type

    if not query:
        return jsonify({"error": "No 'query' found in JSON request"}), 400

    print(f"**query**: {query}")
    print(f"**prompt_type**: {prompt_type}")

    # Dynamically select the prompt based on prompt_type
    prompt = PROMPTS.get(prompt_type)
    if not prompt:
        return jsonify({"error": "Unknown prompt type"}), 400

    try:
        print("Loading vector store")
        vector_store = Chroma(persist_directory=folder_path, embedding_function=embedding)
        db_data = vector_store.get()

        if not db_data.get("metadatas"):
            print("Call ended since there are no documents available to process the query.")
            return jsonify({
                "answer": "No documents available to process your query.",
                "disclaimer": "No documents available to process your query. Upload some PDFs to enable document search.",
                "pdf_usage": {},
                "query_usage": {}
            })

        print("Creating retrieval chain")
        retriever = vector_store.as_retriever(
            search_type="similarity_score_threshold",
            search_kwargs={
                "k": 20,
                "score_threshold": 0.1,
            },
        )

        retriever_prompt = ChatPromptTemplate.from_messages(
            [
                MessagesPlaceholder(variable_name="chat_history"),
                ("human", "{input}"),
                (
                    "human",
                    "Given the above conversation, generate a search query to lookup in order to get information relevant to the conversation",
                ),
            ]
        )
        history_aware_retriever = create_history_aware_retriever(
            llm=cached_llm, retriever=retriever, prompt=retriever_prompt
        )
        document_chain = create_stuff_documents_chain(cached_llm, prompt)

        retrieval_chain = create_retrieval_chain(
            history_aware_retriever,
            document_chain,
        )

        result = retrieval_chain.invoke({"input": query})
        chat_history.append(HumanMessage(content=query))
        chat_history.append(AIMessage(content=result["answer"]))

        print(chat_history)

        sources = create_context_with_metadata(result.get("context", []))

        # Update PDF usage count and query usage count as before
        for doc in result["context"]:
            pdf_source = doc.metadata.get("source")
            if pdf_source in pdf_usage_count:
                pdf_usage_count[pdf_source] += 1
            else:
                pdf_usage_count[pdf_source] = 1

            if pdf_source in query_usage_count:
                query_usage_count[pdf_source] += 1
            else:
                query_usage_count[pdf_source] = 1

        if not sources:
            answer = f"No relevant documents found for the query: {query}. This answer is generated without any PDF context."
        else:
            answer = result["answer"]

        response_answer = {
            "answer": answer,
            "sources": sources,
            "pdf_usage": {pdf: {"count": count, "percentage": (count / sum(pdf_usage_count.values()) * 100) if sum(pdf_usage_count.values()) > 0 else 0} for pdf, count in pdf_usage_count.items()},
            "query_usage": {pdf: {"count": count, "percentage": (count / sum(query_usage_count.values()) * 100) if sum(query_usage_count.values()) > 0 else 0} for pdf, count in query_usage_count.items()},
            "disclaimer": "This answer is not based on any available PDF documents." if not sources else None
        }

        return jsonify(response_answer)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


def create_context_with_metadata(documents):
    contexts = []
    for doc in documents:
        metadata = doc.metadata
        context = f"Document Source: {metadata.get('source', 'Unknown')}\n"
        context += f"Content: {doc.page_content}\n"
        contexts.append({
            "source": metadata.get("source", "Unknown"),
            "page_content": doc.page_content
        })
    return contexts

@bp.route("/clear_chat_history", methods=["POST"])
def clear_chat_history():
    global chat_history
    chat_history = []
    print("Chat history cleared")
    return jsonify({"status": "Chat history cleared successfully"})

@bp.route("/clear_db", methods=["POST"])
def clear_db():
    logging.info("POST /clear_db called")
    try:
        # Clear the vector store (i.e., delete all documents)
        clear_vector_store()

        # Clear the PDF directory if necessary
        clear_directory(pdf_dir)

        # Reinitialize the vector store
        global vector_store
        vector_store = initialize_vector_store()

        return jsonify({"status": "Database and files cleared successfully"})
    except Exception as e:
        logging.error(f"Error during clear_db operation: {str(e)}")
        return jsonify({"error": str(e)}), 500

def clear_directory(directory_path):
    """
    Clears the specified directory by removing it and then recreating it.
    """
    if os.path.exists(directory_path):
        shutil.rmtree(directory_path)
        os.makedirs(directory_path)

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - PDF Interaction Dashboard</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="/static/css/style.css">
    <script src="/static/js/home.js" defer></script>
    <script src="/static/js/script.js" defer></script>
</head>
<body>
    <header>
        <div class="header-content">
            <div class="title-wrapper">
                <h1>
                    <span class="welcome">Welcome to</span> AskItRight
                </h1>
                <div class="ai-powered">
                    AI-Powered PDF Query App (Ollama3.1) 🚀
                </div>
            </div>
            <h2>Document Interaction Dashboard</h2>
            <p>Manage your PDFs, ask questions, and view usage statistics all in one place.</p>
        </div>
    </header>    
    <div class="container card">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-logo">
                    <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Header Image" class="header-image">
                </div>
                <div class="navbar-links">
                    <a href="{{ url_for('main.home') }}" class="nav-link">Home</a>
                    <a href="{{ url_for('main.pdfManagement') }}" class="nav-link" onclick="handleNavigation(event)">PDF Management</a>
                    <!-- Add more links here as needed -->
                </div>
            </div>
        </nav>
        <div class="section-group">
            <div class="card section">
                <div class="pdf-query-section">
                    <h2>Ask About PDF Content</h2>
                    <div id="promptContainer">
                        <p>Use the dropdown menu below to choose an appropriate prompt template...</p>
                        <select id="promptType">
                            <!-- Options populated by JavaScript -->
                        </select>
                    </div>
                    <input type="text" id="queryPDF" placeholder="Type your question about the PDF/s">
                    <button id="askPDFButton" onclick="askPDF()">Submit</button>
                    <div id="queryResponseContainer" class="response-container">
                        <div id="queryResponse" class="response">
                            <!-- Response content goes here -->
                        </div>
                        <div class="resize-handle"></div>
                    </div>
                    <button onclick="clearChatHistory()" style="margin-top: 10px;">Clear Chat History</button>
                    <span style="margin-left: 10px;"></span>
                    <span id="chatHistoryStatus" class="status-message"></span>
                </div>
            </div>
        </div>
        
        <div class="section-group">
            <div class="card section">
                <div class="query-section">
                    <h2>Ask AI</h2>
                    <p>Submit your questions to Ollama3.1 AI model with no embedding from PDFs. I would use this mostly to compare answers</p>
                    <input type="text" id="query" placeholder="Type your question here to the AI model without PDF">
                    <button id="askAIButton" onclick="askAI()">Submit</button>
                    <button onclick="copyTextAndSubmit()">Copy Prompt from ASKPDF & Submit</button>
                    <div id="queryResponseContainerAI" class="response-container">
                        <div id="queryResponseAI" class="response">
                            <!-- Response content goes here -->
                        </div>
                        <div class="resize-handle"></div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="section-group">
            <div class="card section">
                <h2>Usage Statistics</h2>
                <div class="query-usage-section">
                    <h3>Query Usage Statistics</h3>
                    <p>View statistics on how frequently different queries are made to the AI and PDF content.</p>
                    <div id="queryUsageStats" class="stats"></div>       
                </div>
                <div class="pdf-usage-section">
                    <h3>PDF Usage Statistics</h3>
                    <p>Monitor how often each uploaded PDF is accessed or queried within the system.</p>
                    <div id="pdfUsageStats" class="stats"></div>
                </div>
            </div>
        </div>

        <div class="navigation">
            <a href="{{ url_for('main.pdfManagement') }}" class="button" onclick="handleNavigation(event)">PDF Management</a>
        </div>    
    </div>
</body>
<footer>
    <div class="footer-content">
        <p>© 2024 Abd Alsattar Ardati. Created for exploration, learning, and sharing. 📚🔍</p>
        <p>Licensed under Apache 2.0. Visit <a href="https://abd.ardati.org" target="_blank">abd.ardati.org</a> 🌐</p>
    </div>
</footer>
</html>

app/templates/pdfManagement.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF Management</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="static/js/script.js" defer></script>
</head>

<body>
    <header>
        <div class="header-content">
            <div class="title-wrapper">
                <h1>
                    <span class="welcome">Welcome to</span> AskItRight
                </h1>
                <div class="ai-powered">
                    AI-Powered PDF Query App (Ollama3.1) 🚀
                </div>
            </div>
            <h2>PDF Management & Statistics Dashboard</h2>
            <p>View statistics related to the uploaded PDFs and documents in the system.</p>
        </div>
    </header> 

    <div class="container card">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-logo">
                    <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Header Image" class="header-image">
                </div>
                <div class="navbar-links">
                    <a href="{{ url_for('main.home') }}" class="nav-link">Home</a>
                    <a href="{{ url_for('main.pdfManagement') }}" class="nav-link" onclick="handleNavigation(event)">PDF Management</a>
                    <!-- Add more links here as needed -->
                </div>
            </div>
        </nav>

        <div class="section-group">
            <div class="card section">
                <div class="upload-section">
                    <h2>Upload New PDF</h2>
                    <p>Upload a new PDF document to be processed and made available for querying.</p>
                    <input type="file" id="pdfFile">
                    <button onclick="uploadPDF()">Upload</button>
                </div>
            </div>
        </div>

        <div class="section-group">
            <div class="card section">
                <div class="pdf-list-section">
                    <h2>Available PDF Documents</h2>
                    <p>View and access the list of PDFs that have been uploaded to the system.</p>
                    <button onclick="listPDFs()">List PDFs</button>
                    <ul id="pdfList"></ul>
                </div>
            </div>
        </div>

        <div class="section-group">
            <div class="card section">
                <div class="clear-db-section">
                    <h2>Database and File Management</h2>
                    <p>Clear all stored data and uploaded files from the system. Use this carefully as it will delete all records.</p>
                    <button class="primary" onclick="clearDatabase()">Clear Database</button>
                </div>
            </div>
        </div>

        <div class="section-group">
            <div class="card section">
                <h2>PDF Statistics</h2>
                <p>Total PDFs: {{ pdf_count }}</p>
            </div>
        </div>

        <div class="section-group">
            <div class="card section">
                <h2>Document Statistics</h2>
                <p>Total Documents in Chroma DB: {{ doc_count }}</p>
            </div>
        </div>

        <div class="navigation">
            <a href="{{ url_for('main.home') }}" class="button">Back to Home</a>
        </div>
    </div>

    <footer>
        <div class="footer-content">
            <p>© 2024 Abd Alsattar Ardati. Created for exploration, learning, and sharing. 📚🔍</p>
            <p>Licensed under Apache 2.0. Visit <a href="https://abd.ardati.org" target="_blank">abd.ardati.org</a> 🌐</p>
        </div>
    </footer>
</body>

</html>